# @name get-prompts
GET http://localhost:3333/prompts

###

# @name post-videos
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="example.mp3"
Content-Type: audio/mpeg

< ./example.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription
POST http://localhost:3333/videos/469bd624-4777-413e-b3bc-b150031b7c47/transcription
Content-Type: application/json

{
  "prompt": "clean architecture, ddd"
}

###

# @name generate-ai-completion
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
  "videoId": "469bd624-4777-413e-b3bc-b150031b7c47",
  "temperature": 0.5,
  "prompt": "Gere um breve resumo da transcrição do vídeo informado: '''{transcription}'''"
}